included:
  - DevcapApp

excluded:
  - DevcapApp/Bridge/devcap.h

# Rules matching the project's Swift 6 / SwiftUI style
opt_in_rules:
  - closure_spacing
  - collection_alignment
  - empty_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - unowned_variable_capture
  - vertical_whitespace_closing_braces

disabled_rules:
  - todo
  - trailing_comma

line_length:
  warning: 150
  error: 200
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 800

function_body_length:
  warning: 50
  error: 80

identifier_name:
  min_length: 1
  max_length: 60
