name: DevcapApp
options:
  bundleIdPrefix: com.konradmichalik
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

targets:
  DevcapApp:
    type: application
    platform: macOS
    sources:
      - DevcapApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.konradmichalik.devcap
        PRODUCT_NAME: DevcapApp
        MARKETING_VERSION: "0.4.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: DevcapApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: DevcapApp/DevcapApp.entitlements
        LIBRARY_SEARCH_PATHS: "$(PROJECT_DIR)/devcap-ffi/target/release"
        HEADER_SEARCH_PATHS: "$(PROJECT_DIR)/DevcapApp/Bridge"
        OTHER_LDFLAGS: "-ldevcap_ffi"
        SWIFT_OBJC_BRIDGING_HEADER: "DevcapApp/Bridge/devcap.h"

    preBuildScripts:
      - name: Build Rust FFI
        script: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cd "$PROJECT_DIR/devcap-ffi"
          cargo build --release 2>&1
        basedOnDependencyAnalysis: false
